## Day 30 Lecture 1 Assignment

In this assignment, we will build our first random forest model. We will use a dataset containing churn information for a telephone company's customers.

In [ ]:
!pip install category_encoders

     |████████████████████████████████| 81kB 1.2MB/s 


In [ ]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from category_encoders.leave_one_out import LeaveOneOutEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import sklearn
from sklearn.metrics import roc_curve, precision_recall_curve, roc_auc_score

Read in the telecom churn dataset.

https://raw.githubusercontent.com/Thinkful-Ed/data-science-lectures/master/telecom_churn.csv

In [ ]:
# answer here
churn_org = pd.read_csv('https://raw.githubusercontent.com/Thinkful-Ed/data-science-lectures/master/telecom_churn.csv')
churn_org.head()


CustomerID Churn  MonthlyRevenue  ...  PrizmCode    Occupation  MaritalStatus
0     3000002   Yes           24.00  ...   Suburban  Professional             No
1     3000010   Yes           16.99  ...   Suburban  Professional            Yes
2     3000014    No           38.00  ...       Town        Crafts            Yes
3     3000022    No           82.28  ...      Other         Other             No
4     3000026   Yes           17.14  ...      Other  Professional            Yes

[5 rows x 58 columns]

Perform the following preprocessing steps:

- This dataset has many columns; identify a subset of 10-15 features that you think could affect a customer's propensity to churn (also called "customer loss" or "customer attrition"). Include at least 1 categorical variable.
- Drop all rows that containing any missing values (this should be a fairly small number of rows)
- Convert the response from a string to a binary 1-0 encoding.

In [ ]:
churn.head()

Churn  MonthlyRevenue  ...  BlockedCalls    Occupation
0      1           24.00  ...           0.7  Professional
1      1           16.99  ...           0.0  Professional
2      0           38.00  ...           0.0        Crafts
3      0           82.28  ...           7.7         Other
4      1           17.14  ...           0.0  Professional

[5 rows x 12 columns]

In [ ]:
# answer goes here
churn = churn_org.iloc[:, 1:12]

In [ ]:
churn.Churn = churn.Churn.replace(to_replace=['No', 'Yes'], value=[0, 1])

In [ ]:
churn = pd.concat([churn,churn_org['Occupation']], axis=1)

In [ ]:
churn = churn.dropna(axis=0)

Although some implementations of tree-based models support categorical variables directly, scikit-learn's implementation does not, so we will need to convert our categorical variable(s) into numbers. In linear regression, we used one-hot/dummy encoding, but this has drawbacks that can be particularly problematic in the context of trees. Namely, dummy encoding can lead to very sparse columns when dealing with high-dimensional categorical features; the tree treats these levels as indepedent features is very unlikely to make a split on any of the individual levels, since the corresponding columns consist almost entirely consist of a single value.

Ideally, we would consider all of the levels simultaneously, which trees can do efficiently. However, sklearn does not implement this efficient algorithm for splitting on categorical variables. In this situation, a better alternative to dummy encoding is leave-one-out-encoding. This transforms each categorical into its conditional probability of the positive class, excluding the observation itself to avoid potential data leakage. Perform the following steps:

- Create an 80-20 train/test split on the data
- Fit a leave-one-out encoder to the training data and encode the categorical variables in the training data. The category_encoders package is helpful for this task. (Note that this ordering is important; if we fitted the encoder to the full dataset before making the train/test split, we would introduce data leakage by allowing the test data to affecting the estimates of the category-conditional probabilities.)

In [ ]:
# answer goes here
X = churn.drop('Churn', axis=1)
y = churn['Churn']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
cc = LeaveOneOutEncoder(cols=['Occupation'])
X_train = cc.fit_transform(X_train, y_train)
#cc.transform(X_train, y_train)


/usr/local/lib/python3.6/dist-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


Next, fit the random forest model. You can tinker with or tune the parameters if you like, although we will use the default parameter values.

In [ ]:
# answer goes here
rf = RandomForestClassifier()
rf.fit(X_train, y_train)




RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

To evaluate our model, produce the predicted values for the test sample. Remember to apply our previously fitted encoder to the test data prior to making predictions.

In [ ]:
# answer goes here

X_test = cc.fit_transform(X_test, y_test)



/usr/local/lib/python3.6/dist-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


In [ ]:
pred = rf.predict(X_test)

After making the predictions, print out the classification report (sklearn.metrics.classification_report). In addition, plot the confusion matrix and ROC curve. How did our model perform?

In [ ]:
# answer goes here
print(classification_report(y_test, pred))
sklearn.metrics.confusion_matrix(y_test,pred)


              precision    recall  f1-score   support

           0       0.67      0.18      0.29      7241
           1       0.27      0.77      0.40      2895

    accuracy                           0.35     10136
   macro avg       0.47      0.48      0.35     10136
weighted avg       0.56      0.35      0.32     10136



array([[1335, 5906],
       [ 662, 2233]])

In [ ]:
roc_curve(y_test,pred)

(array([0.       , 0.8156332, 1.       ]),
 array([0.        , 0.77132988, 1.        ]),
 array([2, 1, 0]))

Print the feature importances, ordered by importance from high to low. What is the default sklearn feature importance metric?

In [ ]:
# answer goes here

feat_importances = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)

feat_importances

Occupation               0.887152
MonthlyMinutes           0.018247
PercChangeMinutes        0.017425
MonthlyRevenue           0.014579
PercChangeRevenues       0.013780
DroppedCalls             0.010561
TotalRecurringCharge     0.010239
OverageMinutes           0.008873
BlockedCalls             0.008117
DirectorAssistedCalls    0.005528
RoamingCalls             0.005498
dtype: float64