## Day 33 Lecture 2 Assignment

In this assignment, we will learn about non linear SVM models. We will use the heart disease dataset loaded below and analyze the model generated for this dataset.

In [30]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [31]:
heart = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/framingham_heart_disease.csv')

In [32]:
heart.shape

(4238, 16)

In [33]:
heart.head()

male  age  education  currentSmoker  ...    BMI  heartRate  glucose  TenYearCHD
0     1   39        4.0              0  ...  26.97       80.0     77.0           0
1     0   46        2.0              0  ...  28.73       95.0     76.0           0
2     1   48        1.0              1  ...  25.34       75.0     70.0           0
3     0   61        3.0              1  ...  28.58       65.0    103.0           1
4     0   46        3.0              1  ...  23.10       85.0     85.0           0

[5 rows x 16 columns]

This dataset helps us predict the probability of coronary heart diease (CHD) in the next 10 years given the risk factors for each subject in the study. Our target variable is `TenYearCHD`.

We'll start off by removing any rows containing missing data.

In [34]:
# answer below:
X = heart.dropna()


Then, we split the data into train and test with 20% of the data in the test subset.

In [35]:
# answer below:
from sklearn.model_selection import train_test_split

y = X['TenYearCHD']
X = X.drop(columns=['TenYearCHD'])

SIZE=0.2
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=SIZE)

We will then scale the data using the standard scaler. Do this in the cell below.

Generate a polynomial SVC model and a RBF SVC model. Compare the performance, and the runtime, for the two models.

In [36]:
# answer below:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import SVC

poly = make_pipeline(StandardScaler(), SVC(gamma='auto', kernel='poly'))
poly.fit(X, y)

print(classification_report(y_test, poly.predict(X_test)), '\n')
print(classification_report(y_train, poly.predict(X_train)))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92       612
           1       1.00      0.11      0.20       120

    accuracy                           0.85       732
   macro avg       0.93      0.55      0.56       732
weighted avg       0.88      0.85      0.80       732
 

              precision    recall  f1-score   support

           0       0.87      1.00      0.93      2487
           1       0.99      0.15      0.26       437

    accuracy                           0.87      2924
   macro avg       0.93      0.58      0.60      2924
weighted avg       0.89      0.87      0.83      2924



In [37]:
# answer below:
rbf = make_pipeline(StandardScaler(), SVC(gamma='auto', kernel='rbf'))
rbf.fit(X, y)

print(classification_report(y_test, rbf.predict(X_test)), '\n')
print(classification_report(y_train, rbf.predict(X_train)))

              precision    recall  f1-score   support

           0       0.84      1.00      0.92       612
           1       1.00      0.06      0.11       120

    accuracy                           0.85       732
   macro avg       0.92      0.53      0.51       732
weighted avg       0.87      0.85      0.78       732
 

              precision    recall  f1-score   support

           0       0.86      1.00      0.93      2487
           1       1.00      0.09      0.16       437

    accuracy                           0.86      2924
   macro avg       0.93      0.54      0.54      2924
weighted avg       0.88      0.86      0.81      2924



In [38]:
print("POLY:\n train: {} \n test: {} \n RBF:\n train: {} \n test: {}".format( poly.score(X_train, y_train), poly.score(X_test, y_test), rbf.score(X_train, y_train), rbf.score(X_test, y_test)))

POLY:
 train: 0.8727770177838577 
 test: 0.8538251366120219 
 RBF:
 train: 0.8638850889192886 
 test: 0.8456284153005464


Which model overfits more? How would you improve the overfitting?

Look at a classification report and confusion matrix. How does the class balance affect your results?

They both overfit pretty bigtime. Would adjusting my c parameter help with overfitting? How do I even get a total recall and precision that's greater than one? That's just odd. Classification report is above. 

In [41]:
# answer below:
print("Polynomial Confusion")
print(confusion_matrix(y_train, poly.predict(X_train)))
print(confusion_matrix(y_test, poly.predict(X_test) ))


print("RBF Confusion")
print(confusion_matrix(y_train, rbf.predict(X_train)))
print(confusion_matrix(y_test, rbf.predict(X_test) ))




Polynomial Confusion
[[2486    1]
 [ 371   66]]
[[612   0]
 [107  13]]
RBF Confusion
[[2487    0]
 [ 398   39]]
[[612   0]
 [113   7]]
