## Day 49 Lecture 2 Assignment

In this assignment, we will apply mean shift clustering to a dataset containing the results of a survey on financial wellbeing.

In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import MeanShift
from sklearn.preprocessing import StandardScaler

This dataset contains the results of a survey on a financial wellbeing conducted by the US Consumer Finance Protection Bureau that were published in October 2017. This dataset has a large number of columns, most of which correspond to specific questions on the survey. These codebook for translating the column names to questions can be found here:

https://s3.amazonaws.com/files.consumerfinance.gov/f/documents/cfpb_nfwbs-puf-codebook.pdf

Load the dataset.

In [2]:
# answer goes here
df = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/Data%20Sets%20Clustering/financial_wellbeing.csv')
df.head()




PUF_ID  sample  fpl  SWB_1  ...  PPT1317  PPT18OV  PCTLT200FPL   finalwt
0   10350       2    3      5  ...        0        1            0  0.367292
1    7740       1    3      6  ...        0        2            0  1.327561
2   13699       1    3      4  ...        1        2            1  0.835156
3    7267       1    3      6  ...        0        1            0  1.410871
4    7375       1    3      4  ...        0        4            1  4.260668

[5 rows x 217 columns]

While the survey questions have the potential for interesting cluster analysis, we will stick to the "score" columns to avoid clustering in an unreasonably high-dimensional space. The columns we are interested in all have "score" in their names; identify and isolate these columns. (There should be 4 in total.)

In [6]:
# answer goes here
cols = [col for col in df.columns if 'score' in col]
df = df[cols]
df.reset_index(inplace=True)
df.drop(columns='index', inplace=True)
df

FWBscore  FSscore  LMscore  KHscore
0           55       44        3    1.267
1           51       43        3   -0.570
2           49       42        3   -0.188
3           49       42        2   -1.485
4           49       42        1   -1.900
...        ...      ...      ...      ...
6389        61       47        3    1.267
6390        59       59        1   -1.215
6391        59       51        2   -1.215
6392        46       54        2   -1.215
6393        49       42        2   -1.215

[6394 rows x 4 columns]

Standardize the features in your dataset using scikit-learn's StandardScaler, which will set the mean of each feature to 0 and the variance to 1.

In [8]:
# answer goes here
scaler = StandardScaler()
X = scaler.fit_transform(df)



Run mean shift clustering on the scores in the survey dataset using the default bandwidth. Then answer the following by printing or typing as appropriate:

- How many clusters are produced? 
- What are the cluster centers?
- How many responses are assigned to each cluster?
- Are these results reasonable? If not, what changes should we make?

# NO!

*this is not reasonable*

In [9]:
# answer goes here
clustering = MeanShift().fit(X)
clustering.labels_



array([0, 0, 0, ..., 0, 0, 0])

In [12]:
np.unique(clustering.labels_)

array([0, 1])

In [13]:
clustering.cluster_centers_

array([[ 0.09918758, -0.04722472,  0.40797515,  0.33667793],
       [-4.02966165, -4.08655136, -2.98779955, -2.17097301]])

In [14]:
pred = clustering.predict(X)

In [22]:
y = np.bincount(pred)
y

array([6326,   68])

# Changes 

Try changing the appropriate parameters of the mean shift algorithm to achieve a better clustering result. Answer all of the same questions from the previous clustering step.

In [39]:
# answer goes here
# answer goes here
clustering = MeanShift(bandwidth=0.93).fit(X)
pred = clustering.predict(X)
clustering.labels_
np.unique(clustering.labels_)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51])

In [40]:
y = np.bincount(pred)
y

array([3130, 1399,  404,   78,  103,   32,  107,   29,   72,   17,   10,
        120,   93,    7,  103,   26,   16,   40,   12,  103,    4,   13,
         43,    3,    2,    2,    2,   66,    4,    1,   19,  114,    1,
         11,    2,   10,    4,    5,    1,    2,   17,    2,    9,    9,
         13,    9,    7,   73,   36,    7,    1,    1])

In [41]:
clustering.cluster_centers_

array([[ 2.50841260e-01,  4.08922550e-02,  6.53830324e-01,
         5.46649222e-01],
       [-2.55420592e-01, -4.54452471e-01, -6.70398720e-01,
        -6.95988281e-01],
       [-4.85148428e-01, -7.09390322e-01, -1.99462776e+00,
        -1.22577758e+00],
       [-4.62377971e-01, -5.56706758e-01, -3.31885681e+00,
        -1.65194815e+00],
       [ 7.67210210e-01,  2.48292644e+00, -6.70398720e-01,
        -9.45890010e-01],
       [-6.04500078e-01,  1.80516991e+00, -1.99462776e+00,
        -1.65875593e+00],
       [ 1.65794970e+00,  2.49677960e+00, -6.70398720e-01,
        -3.96237846e-01],
       [-1.72282301e+00,  1.93039046e+00, -1.99462776e+00,
        -1.71096206e+00],
       [-1.27024773e+00,  1.71661278e+00, -6.70398720e-01,
        -6.12718547e-01],
       [ 5.19399950e-02,  2.07656699e+00, -1.99462776e+00,
        -8.36171423e-01],
       [ 1.26935513e+00,  2.55065301e+00, -1.99462776e+00,
        -1.74313109e+00],
       [ 2.23730887e+00,  2.52694871e+00, -6.70398720e-01,
      

I tried a whole bunch of different bandwidths varying from .1 to 5. It's not making me happy. 

It looks like the data is just much denser in one area than the other. The default, two, most likely the best selection. I seem to get a much heavier base in one cluster than the others, no matter what. The bulk of the variance must surround that first cluster more. 

perhaps i was being rash. The two could be a the best bandwidth. 