## Day 35 Lecture 2 Assignment

In this assignment, we will combine what we have learned so far about classification algorithms this week.

In [36]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

%matplotlib inline

In [37]:
admission = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/Admission_Predict.csv')

In [38]:
admission.head()
#admission.columns

Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit 
0           1        337          118  ...  9.65         1              0.92
1           2        324          107  ...  8.87         1              0.76
2           3        316          104  ...  8.00         1              0.72
3           4        322          110  ...  8.67         1              0.80
4           5        314          103  ...  8.21         0              0.65

[5 rows x 9 columns]

In this assignment, we will predict the probability of a student being admitted to a PhD program given their stats. To make the predictions, find the median for the Chance of Admit column. Create an admit column where all probabilities above the median will receive a 1 for that column and all probabilities below the median will be a zero.

Below you will process and clean the data, try the SVM classifier, the gradient boosted decision tree classifier and XGBoost, and compare your results.

Have fun!

In [39]:
# Answer below:

In [40]:
#admission['Chance of Admit '].median()

In [ ]:
#admission['admit'] = np.where(admission['Chance of Admit '] >= admission['Chance of Admit '].median(), 1, 0)

In [41]:
admission['Chance of Admit '] = admission['Chance of Admit '] >= admission['Chance of Admit '].median()

In [42]:
admission['Chance of Admit '].value_counts()

True     204
False    196
Name: Chance of Admit , dtype: int64

In [43]:
admission = pd.concat([admission,pd.get_dummies(admission['Chance of Admit '], prefix='Admit', drop_first=True)], axis=1)

In [44]:
admission.drop(columns='Chance of Admit ', inplace=True)

In [45]:
admission['Admit_True'].value_counts()

1    204
0    196
Name: Admit_True, dtype: int64

In [46]:
admission.isnull().sum()*100/admission.isnull().count()


Serial No.           0.0
GRE Score            0.0
TOEFL Score          0.0
University Rating    0.0
SOP                  0.0
LOR                  0.0
CGPA                 0.0
Research             0.0
Admit_True           0.0
dtype: float64

In [47]:
# answer below:
from sklearn.model_selection import train_test_split

X = admission.drop(columns='Admit_True')
y = admission['Admit_True']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
print("The number of observations in training set is {}".format(X_train.shape[0]))
print("The number of observations in test set is {}".format(X_test.shape[0]))

The number of observations in training set is 320
The number of observations in test set is 80


In [48]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [50]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [55]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train_scale, y_train)

print(svc.score(X_train_scale, y_train))
print(svc.score(X_test_scale, y_test))


y_pred = svc.predict(X_test_scale)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.921875
0.8375
[[32  6]
 [ 7 35]]
              precision    recall  f1-score   support

           0       0.82      0.84      0.83        38
           1       0.85      0.83      0.84        42

    accuracy                           0.84        80
   macro avg       0.84      0.84      0.84        80
weighted avg       0.84      0.84      0.84        80



In [56]:
from sklearn.ensemble import GradientBoostingClassifier as GBC

gbc = GBC()
gbc.fit(X_train_scale, y_train)

print(gbc.score(X_train_scale, y_train))
print(gbc.score(X_test_scale, y_test))


y_pred1 = gbc.predict(X_test_scale)
print(confusion_matrix(y_test, y_pred1))
print(classification_report(y_test, y_pred1))

0.996875
0.8125
[[33  5]
 [10 32]]
              precision    recall  f1-score   support

           0       0.77      0.87      0.81        38
           1       0.86      0.76      0.81        42

    accuracy                           0.81        80
   macro avg       0.82      0.82      0.81        80
weighted avg       0.82      0.81      0.81        80



In [53]:
!pip install xgboost

In [57]:
from xgboost import XGBClassifier as XGBC

xgbc = XGBC()
xgbc.fit(X_train_scale, y_train)

print(xgbc.score(X_train_scale, y_train))
print(xgbc.score(X_test_scale, y_test))


y_pred2 = xgbc.predict(X_test_scale)
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

0.978125
0.825
[[33  5]
 [ 9 33]]
              precision    recall  f1-score   support

           0       0.79      0.87      0.82        38
           1       0.87      0.79      0.82        42

    accuracy                           0.82        80
   macro avg       0.83      0.83      0.82        80
weighted avg       0.83      0.82      0.82        80



In [58]:
print('Support Vector Score: ', svc.score(X_test_scale, y_test))

print('Gradient Boost Score: ', gbc.score(X_test_scale, y_test))

print('XGBoost Score: ', xgbc.score(X_test_scale, y_test))


Support Vector Score:  0.8375
Gradient Boost Score:  0.8125
XGBoost Score:  0.825
